title: Kacper Gondro
description: 
  <p align="center">
  <a href="pdf/CV_Kacper_Gondro.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/kacper-gondro-189995214/">LinkedIn</a> |
  <a href="https://github.com/kacper22g">GitHub</a>
  </p>
  
  <p align="justify">
  I recently acquired a Master's Degree in Economic Analysis at the University of Business and Economics. 
  <br><br>
  I worked with clustering algorithms, predictive models, and basic neural networks. In my previous job in the gaming industry, I used Excel and Python to present best-performing types of Fortune Wheels and propose player segmentation based on the payments sum.
  <br><br>
  </p>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
